# Generated by Django 6.0.6 on 2026-06-23 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="name",
            new_name="service_name",
        ),
        migrations.AddField(
            model_name="subscription",
            name="last_paid_date",
            field=models.DateField(default=datetime.date(2026, 6, 23)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="owner_name",
            field=models.CharField(default="Shreya Sharma", max_length=100),
        ),
    ]
